spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}/${DB_NAME:sms}?useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:kiran}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
